#!/bin/bash
#
# Copyright (C) 2020 Canonical, Ltd.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the the GNU General Public License version 3, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranties of
# MERCHANTABILITY, SATISFACTORY QUALITY or FITNESS FOR A PARTICULAR
# PURPOSE.  See the applicable version of the GNU General Public
# License for more details.
#.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This reference implementation includes a function for generating an
# appropriate key.
# 
# In order to use this wrapper with snapd and snapcraft, export the fully
# qualified path to it e.g.:
# export SNAPD_EXT_KEYMGR=${HOME}/bin/pkcs11-snap-wrapper
# 
# The following commands are expected to be handled by the wrapper, per snapd:
# features
#   output: {"signing": ["RSA-PKCS"], "public-keys": ["DER"]}
#
# key-names
#   output: {"key-names": ["<key 1>", "<key 2>"]}
#   reference: pkcs11-tool -l --pin <pin> --list-objects --type pubkey
#
# get-public-key -f DER -k <key-name>
#   output: to stdout
#   reference: pkcs11-tool -l --pin <pin> --read-object --type pubkey --label <key-name>
#
# sign -m RSA-PKCS -k <key-name>
#   input: from stdin
#   output: to stdout
#   reference: echo "DATA" | pkcs11-tool -s --pin <pin> --label <key-name> -m RSA-PKCS

help() {
  printf "A wrapper for pkcs11-tool intended to be used by snapd|snapcraft\n\n"
  printf "To use this wrapper with snapd and snapcraft, export the fully qualified path to it, e.g.:\n\n"
  printf "\texport SNAPD_EXT_KEYMGR=\${HOME}/bin/pkcs11-snap-wrapper\n\n"
  printf "This wrapper allows using crypto tokens like the Nitrokey HSM to sign assertions.\n\n"
  printf "Supported commands:\n"
  printf "\thelp: this help\n"
  printf "\tfeatures: get the list of features\n"
  printf "\tkey-names: get the list of public key names\n"
  printf "\tlist-keys: get a detailed list of public keys\n"
  printf "\tget-public-key: get a public key\n"
  printf "\t\trequired parameters: -k <key name>, -f <key format/DER>\n"
  printf "\tsign: sign data from stdin\n"
  printf "\t\trequired parameters: -k <key name>, -m <mechanism/RSA-PKCS>\n"
  printf "\tgenerate-key: generate a key suitable for assertion signing\n"
  printf "\t\trequired parameters: -k <key name>, -t <key type/rsa:4096>\n"
}

# features returns the HSM features supported by the wrapper script
features() {
  echo '{"signing": ["RSA-PKCS"], "public-keys": ["DER"]}'
}

# list_keys returns a verbose list of all public keys available in the HSM
list_keys() {
  pkcs11-tool -l --pin env:PKCS11_PIN --list-objects --type pubkey
}

# key_names returns a list of keys by label stored in the HSM
key_names() {
  key_names="$(list_keys                                    |
               sed -n 's/.*label:[[:space:]]*\(.*\)/"\1"/p' |
               tr '\n' ',')"

  [ -n "${key_names}" ] || {
    echo "No keys on HSM! Please create at least one key."
    exit 1
  }

  echo "{\"key-names\": [${key_names::-1}]}"
}

# get_public_key returns a public key specified by label
# Expected: -f DER -k <key-name>
get_public_key() {
  # Check that all parameters are set
  { [ -n "${key_format}" ] && [ -n "${key_name}" ]; } ||
  { echo "Missing required parameter: [key name, key format]"; exit 1; }

  # Check for correct format
  [ "${key_format}" = "DER" ] || { echo "Unsupported key format: ${key_format}"; exit 1; }

  pkcs11-tool -l --pin env:PKCS11_PIN --read-object --type pubkey --label "${key_name}"
}

# sign performs a signing operation with a specified key
# Expected: -m RSA-PKCS -k <key-name>
sign() {
  # Check that all parameters are set
  { [ -n "${mechanism}" ] && [ -n "${key_name}" ]; } ||
  { echo "Missing required parameter: [key name, mechanism]"; exit 1; }

  # There is a bug in pkcs11 for signing operation and the key label is not
  # honoured. Get key ID based on the key name first.
  key_id=$(list_keys                       |
           sed -n '/'"${key_name}"'/{n;p}' |
           awk '{print $2}')

  # Sign input from stdin
  pkcs11-tool -s --pin env:PKCS11_PIN -m "${mechanism}" --id "${key_id}"
}

# generate_key generates a key in the HSM
# Expected key type:size, key name
generate_key() {
  # Check that all parameters are set
  { [ -n "${key_type}" ] && [ -n "${key_name}" ]; } ||
  { echo "Missing required parameter: [key name, key type]" ; exit 1; }

  # Check for correct type
  [ "${key_type}" = "rsa:4096" ] || { echo "Unsupporrted key type: ${key_type}"; exit 1; }

  # Generate key pair
  pkcs11-tool -l --pin env:PKCS11_PIN --keypairgen --key-type "${key_type}" --label "${key_name}"
}

# PKCS11_PIN must be exported
[ -n "${PKCS11_PIN}" ] || {
  echo "Please export your HSM's user PIN as PKCS11_PIN"
  exit 1
}

# Parse arguments
cmd=${1}; shift
while [ -n "${1}" ]; do
  case ${1} in
    -k) key_name="${2}"; shift   ;;
    -t) # Only rsa:4096 keys are supported
        key_type="${2}"; shift   ;;
    -m) # Only RSA-PKCS mechanism is supported
        mechanism="${2}"; shift  ;;
    -f) # Only DER key format is supported
        key_format="${2}"; shift ;;
    *)  echo "Unsupported argument: ${1}"; exit 1 ;;
  esac

  shift
done

# Handle command
_cmd="${cmd//-/_}"
case ${cmd} in
  features|key-names|list-keys|help)       "$_cmd"    ;;
  sign|generate-key|get-public-key) shift; "$_cmd"    ;;
  *) echo "Unsupported command: ${cmd}"; help; exit 1 ;;
esac
